#!/bin/bash

make re

./antman/antman $1 2 > compressed

ORIGINAL_SIZE=$(stat -c %s $1)
COMPRESSED_SIZE=$(stat -c %s compressed)
let SIZE=($COMPRESSED_SIZE * 100/$ORIGINAL_SIZE)

echo
echo -ne "The file was compressed and reduced to "
echo -ne $SIZE
echo -e "% of its original size"

./giantman/giantman compressed 2 > uncompressed.html

diff $1 uncompressed.html > difference
DIFF_SIZE=$(stat -c %s difference)

if [ $DIFF_SIZE -eq 0 ]
then
    rm difference
    echo "SUCCESS"
    echo
else
    echo "ERROR"
    echo
fi
